export const enUS = {
  ABOUT_ME: 'About me',
  PORTFOLIO: 'Portfolio',
  LOGOUT: 'Logout',
  HI: 'Hi, ',
  DESCRIPTION: 'Hi, This is a sample for custom react component...',
  BACHELOR: 'Bachelor: Applied Mathematics, NUK. 2002/9 - 2006/6',
  MASTER: 'Master: Information Management, NCNU. 2006/9 - 2008/7',
  EDUCATION: 'Education',
  EXPERIENCE: 'Experience',
  EXPERIENCE_1: 'Software Architecture, FUTABA. 2010/7 - 2015/10',
  EXPERIENCE_2: 'Technical Management, Wistron. 2015/11 - Present',
  EXPERIENCE_3: 'To Be Continue...',
  SKILLS: 'Skills',
  SKILLS_1: 'Frontend development：ReactJS, AugularJS, JQuery, CSS, HTML, .Net Application (Window Form, Web Form)',
  SKILLS_2: 'Backend development：.Net Web API, .Net Core, nodejs, Web Service, Azure, AWS',
  MOTTO: 'Motto',
  MOTTO_1: 'Music Makes Life Better',
  CONTACT: 'Contact',
  CONTACT_1: 'Email-Address: npkalala@gmail.com',
  BADGE: 'Badge',
  CARD: 'Card',
  BUY: 'Buy it',
  RECOMMAND: 'Recommand',
  RING_CHART: 'Ring Chart',
  MIX_CHART: 'Mix Chart'
};
