export const zhTW = {
  ABOUT_ME: '關於我',
  PORTFOLIO: '範例集',
  LOGOUT: '登出',
  HI: '嗨，',
  DESCRIPTION: '您好，這是一個React Component的範例程式...',
  BACHELOR: '學士: 國立高雄大學 應用數學系 2002/9 - 2006/6',
  MASTER: '碩士: 國立暨南國際大學 資訊管理所 2006/9 - 2008/7',
  EDUCATION: '教育',
  EXPERIENCE: '經歷',
  EXPERIENCE_1: '台灣雙葉電子 系統架構師 2010/7 - 2015/10',
  EXPERIENCE_2: '緯創資通 主任 2015/11 - Present',
  EXPERIENCE_3: '持續更新中...',
  SKILLS: '專長',
  SKILLS_1: '前端開發：ReactJS, AugularJS, JQuery, CSS, HTML, .Net Application (Window Form, Web Form)',
  SKILLS_2: '後端開發：.Net Web API, .Net Core, nodejs, Web Service, Azure, AWS',
  MOTTO: '座右銘',
  MOTTO_1: '音樂讓生活更美好',
  CONTACT: '聯絡方式',
  CONTACT_1: '電子郵件: npkalala@gmail.com',
  BADGE: '徽章',
  CARD: '卡片',
  BUY: '放入購物車',
  RECOMMAND: '阿彥推薦',
  RING_CHART: '環圖',
  MIX_CHART: '綜合線圖',
};
